name: simple_knn
version: 0.0.1
description: Calculate k-nearest neighbours(knn) with a small subset of lodash with chaining capability
homepage: https://github.com/schilken/simple_knn

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.0.0
